const vm = new Vue({
    el: '#app',
    data: function() {
      return { 
          value:"",
          options:[],
          carList:[
              {
                logo:"images/ico_honda.png",
                image:"images/car_01.png",
                name:"本田歌诗途",
                model:"CRV",
                priece:39800,
                date_production:"200201",
                register:"200205"
              },
              {
                logo:"images/ico_honda.png",
                image:"images/car_02.png",
                name:"本田歌诗途",
                model:"CRV",
                priece:39800,
                date_production:"200201",
                register:"200205"
              },
              {
                logo:"images/ico_bmw.png",
                image:"images/car_03.png",
                name:"本田歌诗途",
                model:"CRV",
                priece:39800,
                date_production:"200201",
                register:"200205"
              },
              {
                logo:"images/ico_bmw.png",
                image:"images/car_04.png",
                name:"本田歌诗途",
                model:"CRV",
                priece:39800,
                date_production:"200201",
                register:"200205"
              },
              {
                logo:"images/ico_honda.png",
                image:"images/car_01.png",
                name:"本田歌诗途",
                model:"CRV",
                priece:39800,
                date_production:"200201",
                register:"200205"
              },
              {
                logo:"images/ico_honda.png",
                image:"images/car_02.png",
                name:"本田歌诗途",
                model:"CRV",
                priece:39800,
                date_production:"200201",
                register:"200205"
              },
              {
                logo:"images/ico_bmw.png",
                image:"images/car_03.png",
                name:"本田歌诗途",
                model:"CRV",
                priece:39800,
                date_production:"200201",
                register:"200205"
              },
              {
                logo:"images/ico_bmw.png",
                image:"images/car_04.png",
                name:"本田歌诗途",
                model:"CRV",
                priece:39800,
                date_production:"200201",
                register:"200205"
              },
              {
                logo:"images/ico_honda.png",
                image:"images/car_01.png",
                name:"本田歌诗途",
                model:"CRV",
                priece:39800,
                date_production:"200201",
                register:"200205"
              },
              {
                logo:"images/ico_honda.png",
                image:"images/car_02.png",
                name:"本田歌诗途",
                model:"CRV",
                priece:39800,
                date_production:"200201",
                register:"200205"
              },
              {
                logo:"images/ico_bmw.png",
                image:"images/car_03.png",
                name:"本田歌诗途",
                model:"CRV",
                priece:39800,
                date_production:"200201",
                register:"200205"
              },
              {
                logo:"images/ico_bmw.png",
                image:"images/car_04.png",
                name:"本田歌诗途",
                model:"CRV",
                priece:39800,
                date_production:"200201",
                register:"200205"
              },
              {
                logo:"images/ico_honda.png",
                image:"images/car_01.png",
                name:"本田歌诗途",
                model:"CRV",
                priece:39800,
                date_production:"200201",
                register:"200205"
              },
              {
                logo:"images/ico_honda.png",
                image:"images/car_02.png",
                name:"本田歌诗途",
                model:"CRV",
                priece:39800,
                date_production:"200201",
                register:"200205"
              },
              {
                logo:"images/ico_bmw.png",
                image:"images/car_03.png",
                name:"本田歌诗途",
                model:"CRV",
                priece:39800,
                date_production:"200201",
                register:"200205"
              },
              {
                logo:"images/ico_bmw.png",
                image:"images/car_04.png",
                name:"本田歌诗途",
                model:"CRV",
                priece:39800,
                date_production:"200201",
                register:"200205"
              },
              
          ],
          HightPriceCarList:[
            {
                logo:"images/ico_honda.png",
                image:"images/car_01.png",
                name:"本田歌诗途",
                model:"CRV",
                priece:39800,
                date_production:"200201",
                register:"200205"
              },
              {
                logo:"images/ico_honda.png",
                image:"images/car_02.png",
                name:"本田歌诗途",
                model:"CRV",
                priece:39800,
                date_production:"200201",
                register:"200205"
              },
              {
                logo:"images/ico_bmw.png",
                image:"images/car_03.png",
                name:"本田歌诗途",
                model:"CRV",
                priece:39800,
                date_production:"200201",
                register:"200205"
              },
              {
                logo:"images/ico_bmw.png",
                image:"images/car_04.png",
                name:"本田歌诗途",
                model:"CRV",
                priece:39800,
                date_production:"200201",
                register:"200205"
              },
              {
                logo:"images/ico_honda.png",
                image:"images/car_01.png",
                name:"本田歌诗途",
                model:"CRV",
                priece:39800,
                date_production:"200201",
                register:"200205"
              },
              {
                logo:"images/ico_honda.png",
                image:"images/car_02.png",
                name:"本田歌诗途",
                model:"CRV",
                priece:39800,
                date_production:"200201",
                register:"200205"
              },
              {
                logo:"images/ico_bmw.png",
                image:"images/car_03.png",
                name:"本田歌诗途",
                model:"CRV",
                priece:39800,
                date_production:"200201",
                register:"200205"
              },
              {
                logo:"images/ico_bmw.png",
                image:"images/car_04.png",
                name:"本田歌诗途",
                model:"CRV",
                priece:39800,
                date_production:"200201",
                register:"200205"
              },
              {
                logo:"images/ico_honda.png",
                image:"images/car_01.png",
                name:"本田歌诗途",
                model:"CRV",
                priece:39800,
                date_production:"200201",
                register:"200205"
              },
              {
                logo:"images/ico_honda.png",
                image:"images/car_02.png",
                name:"本田歌诗途",
                model:"CRV",
                priece:39800,
                date_production:"200201",
                register:"200205"
              },
              {
                logo:"images/ico_bmw.png",
                image:"images/car_03.png",
                name:"本田歌诗途",
                model:"CRV",
                priece:39800,
                date_production:"200201",
                register:"200205"
              },
              {
                logo:"images/ico_bmw.png",
                image:"images/car_04.png",
                name:"本田歌诗途",
                model:"CRV",
                priece:39800,
                date_production:"200201",
                register:"200205"
              },
              {
                logo:"images/ico_honda.png",
                image:"images/car_01.png",
                name:"本田歌诗途",
                model:"CRV",
                priece:39800,
                date_production:"200201",
                register:"200205"
              },
              {
                logo:"images/ico_honda.png",
                image:"images/car_02.png",
                name:"本田歌诗途",
                model:"CRV",
                priece:39800,
                date_production:"200201",
                register:"200205"
              },
              {
                logo:"images/ico_bmw.png",
                image:"images/car_03.png",
                name:"本田歌诗途",
                model:"CRV",
                priece:39800,
                date_production:"200201",
                register:"200205"
              },
              {
                logo:"images/ico_bmw.png",
                image:"images/car_04.png",
                name:"本田歌诗途",
                model:"CRV",
                priece:39800,
                date_production:"200201",
                register:"200205"
              },
          ]
      }
    },
    methods:{
      open(url){
        window.open(url,'')
      }
    }
  })